export const ITEM_CREATE_NEW = '@@redux-data/ITEM_CREATE_NEW'
export const ITEM_ADD = '@@redux-data/ITEM_ADD'
export const ITEM_UPDATE = '@@redux-data/ITEM_UPDATE'

export const ITEM_SAVE = '@@redux-data/ITEM_SAVE'
export const ITEM_RELOAD = '@@redux-data/ITEM_RELOAD'
export const ITEM_DELETE = '@@redux-data/ITEM_DELETE'
export const ITEM_DESTROY = '@@redux-data/ITEM_DESTROY'

export const ITEM_ATTRIBUTES_MAP = '@@redux-data/ITEM_ATTRIBUTES_MAP'
export const ITEM_ATTRIBUTES_ROLLBACK = '@@redux-data/ITEM_ATTRIBUTES_ROLLBACK'
export const ITEM_ATTRIBUTES_SET = '@@redux-data/ITEM_ATTRIBUTES_SET'
export const ITEM_ATTRIBUTE_SET = '@@redux-data/ITEM_ATTRIBUTE_SET'
export const ITEM_ATTRIBUTE_RESET = '@@redux-data/ITEM_ATTRIBUTE_RESET'
export const ITEM_ATTRIBUTE_TOGGLE = '@@redux-data/ITEM_ATTRIBUTE_TOGGLE'
export const ITEM_ATTRIBUTE_DELETE = '@@redux-data/ITEM_ATTRIBUTE_DELETE'

export const ITEM_META_SET = '@@redux-data/ITEM_META_SET'
export const ITEM_META_TOGGLE = '@@redux-data/ITEM_META_TOGGLE'
export const ITEM_META_DELETE = '@@redux-data/ITEM_META_DELETE'
