export const RELATIONSHIP_RESET = '@@redux-data/RELATIONSHIP_RESET'

// one
export const RELATIONSHIP_ONE_SET = '@@redux-data/RELATIONSHIP_ONE_SET'
export const RELATIONSHIP_ONE_DELETE = '@@redux-data/RELATIONSHIP_ONE_DELETE'

// many
export const RELATIONSHIP_MANY_SET = '@@redux-data/RELATIONSHIP_MANY_SET'
export const RELATIONSHIP_MANY_ADD = '@@redux-data/RELATIONSHIP_MANY_ADD'
export const RELATIONSHIP_MANY_DELETE = '@@redux-data/RELATIONSHIP_MANY_DELETE'

// middleware
export const RELATIONSHIP_ONE_FETCH = '@@redux-data/RELATIONSHIP_ONE_FETCH'
export const RELATIONSHIP_MANY_FETCH = '@@redux-data/RELATIONSHIP_MANY_FETCH'

// advanced -- buffered?
export const RELATIONSHIP_MANY_CONCAT = '@@redux-data/RELATIONSHIP_MANY_CONCAT'
export const RELATIONSHIP_MANY_FILTER = '@@redux-data/RELATIONSHIP_MANY_FILTER'
export const RELATIONSHIP_MANY_MAP = '@@redux-data/RELATIONSHIP_MANY_MAP'
export const RELATIONSHIP_MANY_PUSH = '@@redux-data/RELATIONSHIP_MANY_PUSH'
export const RELATIONSHIP_MANY_REVERSE = '@@redux-data/RELATIONSHIP_MANY_REVERSE'
export const RELATIONSHIP_MANY_SLICE = '@@redux-data/RELATIONSHIP_MANY_SLICE'
export const RELATIONSHIP_MANY_SORT = '@@redux-data/RELATIONSHIP_MANY_SORT'
export const RELATIONSHIP_MANY_SPLICE = '@@redux-data/RELATIONSHIP_MANY_SPLICE'
export const RELATIONSHIP_MANY_UNSHIFT = '@@redux-data/RELATIONSHIP_MANY_UNSHIFT'
