import { combineReducers } from 'redux'
import { handleActions } from 'redux-actions'
import reduceReducers from 'reduce-reducers'
import uuid from 'uuid/v4'
import relationshipsReducer from './relationshipsReducer'
import {
  REDUX_DATA_ITEM_CREATE_NEW,
  REDUX_DATA_ITEM_SAVE,
  REDUX_DATA_ITEM_ATTRIBUTES_ROLLBACK,
  REDUX_DATA_ITEM_ATTRIBUTE_TOGGLE
} from '../constants/itemConstants'

import metaReducer from './itemMetaReducer'
import attributesReducer from './attributesReducer'

const identityReducer = (initialState = {}) => (state = initialState) => state

const itemReducer = handleActions({
  [REDUX_DATA_ITEM_CREATE_NEW]: (state, action) => {
    const { payload } = action
    const { type } = payload
    const item = { ...state, meta: state.meta || {} }

    item.meta.isNew = true

    if (!item.id) {
      item.id = uuid()
      item.meta.hasAutogeneratedId = true
    }

    if (!item.type) {
      item.type = type
    }

    return item
  },

  // TODO: save should really be happening in the middleware
  [REDUX_DATA_ITEM_SAVE]: (state, action) => {
    const { changedAttributes } = state.meta
    const item = {
      ...state,
      attributes: { ...state.attributes, ...changedAttributes }
    }

    return item
  },
  [REDUX_DATA_ITEM_ATTRIBUTES_ROLLBACK]: (state, action) => {
    const { meta } = state || {}
    const { changedAttributes, deletedAttributes } = meta
    const hasChangedAttributes = !!changedAttributes && !!Object.keys(changedAttributes).length
    const hasDeletedAttributes = !!deletedAttributes && !!deletedAttributes.length
    const newState = { ...state }
    if (hasChangedAttributes) {
      delete newState.meta.changedAttributes
    }
    if (hasDeletedAttributes) {
      delete newState.meta.deletedAttributes
    }
    newState.meta.isSaved = true

    return newState
  },
  [REDUX_DATA_ITEM_ATTRIBUTE_TOGGLE]: (state, action) => {
    const { payload } = action
    const { attribute } = payload
    const value = state.attributes[attribute]

    const newAction = {
      ...action,
      meta: { ...action.meta, value }
    }
    return { ...state, meta: metaReducer(state.meta, newAction) }
  }
}, {})

// wraps a reducer, skips actions in the constants array
const skipActions = (constants = []) => reducer => (state, action) => {
  if (!constants.includes(action.type)) {
    return reducer(state, action)
  }
  return state
}

export default (state, action) => {
  const { payload } = action
  if (!payload) { return state }

  return reduceReducers(
    itemReducer,
    combineReducers({
      type: identityReducer(''),
      id: identityReducer(''),
      attributes: attributesReducer,
      relationships: relationshipsReducer,
      meta: skipActions([REDUX_DATA_ITEM_ATTRIBUTE_TOGGLE])(metaReducer)
    })
  )(state, action)
}
